version: '3.8'
services:
  my-mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
      MYSQL_PASSWORD: root
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      retries: 5
      interval: 10s
      start_period: 20s
      timeout: 10s

  my-redis:
    image: redis:latest
    container_name: my-redis
    hostname: my-redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  hibernate_final:
      build: ./
      container_name: hibernate_final
      image: hibernate_final
      depends_on:
        my-mysql:
          condition: service_healthy
        my-redis:
          condition: service_started
      ports:
        - "8080:8080"
      networks:
        - my_network

networks:
  my_network:
    driver: bridge